apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yourspace # {"$kpt-set":"namespace-setter"}
  name: wordpress-deployment
spec:
  replicas: 5 # {"$kpt-set":"wordpress-replicas"}
  template:
    spec:
      containers:
      - name: wordpress
        image: wordpress:1.8.1
