apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yourspace
  name: wordpress-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: wordpress
        image: wordpress:1.8.1
